"""
Compiler - generates pack_<lang>.nut files from database.

Output format matches rosetta/pack_ru.nut structure expected by ::Rosetta.add().
"""

import json
from pathlib import Path
from typing import Optional, List, Dict, Any

from .database import Database


def compile_translation(
    db: Database,
    version: str,
    lang: str,
    output_path: Optional[Path] = None,
    author: str = "community"
) -> str:
    """
    Generate .nut file matching ::Rosetta.add() format.

    Args:
        db: Database instance
        version: Game version to compile for
        lang: Target language code (e.g., "ru")
        output_path: Where to write file (None = return string only)
        author: Author name for metadata

    Returns:
        Generated .nut content as string
    """
    strings = db.get_strings_for_compile(version, lang)

    # Build pairs array
    pairs_lines = []
    for s in strings:
        translated = s.get('translated_text') or ''
        if not translated:
            continue  # Skip untranslated strings

        pair = _format_pair(s, lang, translated)
        pairs_lines.append(pair)

    # Generate .nut content (matches pack_ru.nut format)
    content = f'''// Generated by rosetta_db compiler
// Version: {version}, Language: {lang}
// Total pairs: {len(pairs_lines)}

local def = ::Rosetta;
local rosetta = {{
    mod = {{id = def.ID, version = def.Version}}
    author = "{author}"
    lang = "{lang}"
}}
local pairs = [
{_indent_lines(pairs_lines, 4)}
]
def.add(rosetta, pairs);
'''

    if output_path:
        output_path.write_text(content, encoding='utf-8')

    return content


def _format_pair(s: Dict[str, Any], lang: str, translated: str) -> str:
    """Format a single translation pair as Squirrel code."""
    en_text = s['en_text']
    mode = s.get('mode', 'literal')
    context = s.get('context', '')
    file_path = s.get('file_path', '')

    # Escape strings for Squirrel
    en_escaped = _escape_squirrel(en_text)
    trans_escaped = _escape_squirrel(translated)

    lines = []

    # Add context comment
    if file_path or context:
        comment = f"{file_path}::{context}" if context else file_path
        lines.append(f"// {comment}")

    lines.append("{")

    if mode == 'pattern':
        lines.append(f'    mode = "pattern"')

    lines.append(f'    en = "{en_escaped}"')
    lines.append(f'    {lang} = "{trans_escaped}"')
    lines.append("}")

    return '\n'.join(lines)


def _escape_squirrel(s: str) -> str:
    """Escape string for Squirrel string literal."""
    return (s
        .replace('\\', '\\\\')
        .replace('"', '\\"')
        .replace('\n', '\\n')
        .replace('\r', '\\r')
        .replace('\t', '\\t'))


def _indent_lines(lines: List[str], spaces: int) -> str:
    """Indent multiline strings."""
    indent = ' ' * spaces
    result = []
    for line in lines:
        indented = '\n'.join(indent + l for l in line.split('\n'))
        result.append(indented)
    return '\n'.join(result)


def compile_stats(db: Database, version: str, lang: str) -> Dict[str, int]:
    """Get compilation statistics without generating file."""
    strings = db.get_strings_for_compile(version, lang)

    total = len(strings)
    translated = sum(1 for s in strings if s.get('translated_text'))
    patterns = sum(1 for s in strings if s.get('mode') == 'pattern' and s.get('translated_text'))

    return {
        'total': total,
        'translated': translated,
        'untranslated': total - translated,
        'patterns': patterns,
        'coverage': round(100 * translated / total, 1) if total else 0
    }
